SELECT  t4.COLUMN_NAME
       ,t4.TYPE_NAME
FROM TBLS t1
INNER JOIN DBS t2
ON t1.DB_ID= t2.DB_ID
INNER JOIN SDS t3
ON t1.SD_ID = t3.SD_ID
INNER JOIN COLUMNS_V2 t4
ON t3.CD_ID= t4.CD_ID
WHERE t2.NAME='{{ db_name }}' 
AND t1.TBL_NAME = '{{ tb_name }}'
ORDER BY t4.INTEGER_IDX  